# -*- coding: utf-8 -*-
"""Task1_Consultbae.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtwPDy65A_-kFTEiWBEWi-hD1i7fBsBb

# Imports and dependencies
"""

import pandas as pd
import re
from datetime import datetime

"""#Loading the CSV's"""

df1 = pd.read_csv('/content/drive/MyDrive/consultbae_assignment/source1_naukri_applicants.csv')
df2 = pd.read_csv('/content/drive/MyDrive/consultbae_assignment/source2_gig_workers.csv')
df3 = pd.read_csv('/content/drive/MyDrive/consultbae_assignment/source3_cbnexus_contacts.csv')

"""#Null/Empty row handling"""

print(df3.shape)
df3.iloc[14]

df1.dropna(inplace=True)
df2.dropna(inplace=True)
df3.dropna(inplace=True)
df3 = df3.drop(index=14).reset_index(drop=True)
print(df1.shape)
print(df2.shape)
print(df3.shape)

# Confirm the embedded header row is actually gone
print("Any 'Name' == 'Name' rows left?", (df3['Name'] == 'Name').sum())

# Also confirm you didn't accidentally drop a real person instead
print("Shape after drop:", df3.shape)
print(df3.head(20))  # eyeball rows around index 12-16 to make sure a real person wasn't lost

"""#Normalization functions"""

def normalize_email(email):
    return str(email).strip().lower() if pd.notna(email) else None

def normalize_phone(phone):
    """Strip everything down to a bare 10-digit Indian number."""
    if pd.isna(phone):
        return None
    digits = re.sub(r'\D', '', str(phone))
    if len(digits) == 12 and digits.startswith('91'):
        digits = digits[2:]
    if len(digits) == 11 and digits.startswith('0'):
        digits = digits[1:]
    return digits if len(digits) == 10 else None

CITY_MAP = {
    'gurugram': 'gurgaon',
    'delhi ncr': 'delhi',
    'new delhi': 'delhi',
    'bengaluru': 'bangalore',
}

def normalize_city(city):
    if pd.isna(city):
        return None
    return CITY_MAP.get(str(city).strip().lower(), str(city).strip().lower())

def normalize_name(name):
    return re.sub(r'\s+', ' ', str(name).strip()).title() if pd.notna(name) else None

def normalize_status(status):
    return str(status).strip().lower() if pd.notna(status) else None

def normalize_verified(v):
    return str(v).strip().lower() in ('y', 'yes') if pd.notna(v) else None

def normalize_rate(rate_str):
    """Split a rate string into (numeric_value, rate_type)."""
    s = str(rate_str).strip().lower()
    if '/hr' in s:
        return float(s.replace('/hr', '')), 'hourly'
    if 'k/month' in s:
        return float(s.replace('k/month', '')) * 1000, 'monthly'
    return None, None

def normalize_ctc(ctc):
    if pd.isna(ctc):
        return None
    try:
        val = float(ctc)
    except (ValueError, TypeError):
        return None
    if val < 1000:  # e.g. 4.2 -> almost certainly lakhs, not rupees
        return round(val * 100000)
    return round(val)


def normalize_applied_date(date_str):
    if pd.isna(date_str):
        return None
    s = str(date_str).strip()

    known_formats = ['%d-%m-%Y', '%Y-%m-%d', '%d %b %Y', '%m/%d/%Y']
    for fmt in known_formats:
        try:
            return datetime.strptime(s, fmt).strftime('%Y-%m-%d')
        except ValueError:
            continue

    # fallback: let pandas try to infer it
    try:
        return pd.to_datetime(s, dayfirst=True).strftime('%Y-%m-%d')
    except Exception:
        return None

"""#Source1 cleaning and handling"""

df1_final = df1.assign(
    norm_name=df1['Full Name'].apply(normalize_name),
    norm_email=df1['Email'].apply(normalize_email),
    norm_phone=df1['Phone'].apply(normalize_phone),
    norm_city=df1['City'].apply(normalize_city),
    norm_ctc=df1['Current CTC'].apply(normalize_ctc),
    norm_applied_date=df1['Applied Date'].apply(normalize_applied_date),
)[[
    'norm_name', 'norm_email', 'norm_phone', 'norm_city',
    'norm_applied_date', 'norm_ctc', 'Skills', 'Experience (Years)'
]]

# Confirm duplicates
dupes = df1_final[
    df1_final.duplicated(subset=['norm_email', 'norm_phone'], keep=False) &
    df1_final['norm_email'].notna()
]
print("Duplicate rows found:")
display(dupes[['norm_name', 'norm_email', 'norm_phone']])

before = len(df1_final)

# sort so the longer name comes first within each duplicate group
df1_final = df1_final.sort_values('norm_name', key=lambda s: s.str.len(), ascending=False)

# drop rows that share both email and phone, keeping the first (longest name) occurrence
df1_final = df1_final.drop_duplicates(subset=['norm_email', 'norm_phone'], keep='first').reset_index(drop=True)

print(f"{before} -> {len(df1_final)} rows after removing exact duplicate")

df1_final['dedup_group_id'] = df1_final.index  # default: every row is its own group

phone_groups = df1_final[df1_final['norm_phone'].notna()].groupby('norm_phone')

for phone, group in phone_groups:
    if len(group) > 1:
        canonical_idx = group.index[0]  # first row becomes the "canonical" one
        df1_final.loc[group.index, 'dedup_group_id'] = canonical_idx
        print(f"Grouped as one person (shared phone {phone}):")
        display(group[['norm_name', 'norm_email', 'norm_phone', 'norm_city']])

df1_final['Skills'] = df1_final['Skills'].apply(lambda s: ', '.join(x.strip().lower() for x in str(s).split(',')))

df1_final.to_csv('df1_final.csv', index=False)

"""#Source2 cleaning and handling"""

df2_final = df2.assign(
    norm_name=df2['worker_name'].apply(normalize_name),
    norm_email=df2['email_id'].apply(normalize_email),
    norm_loc=df2['location'].apply(normalize_city),
    norm_status=df2['status'].apply(normalize_status),
    norm_rate=df2['rate'].apply(normalize_rate),

)[[
    'norm_name', 'norm_email', 'norm_loc', 'rate' ,'norm_status', 'skill_tags'
]]

df2_final = df2_final[df2_final['norm_email'].str.contains('@', na=False)].reset_index(drop=True)

df2_final[['rate_value', 'rate_type']] = df2_final['rate'].apply(
    lambda x: pd.Series(normalize_rate(x)))

df2_final.to_csv('df2_final.csv', index=False)

"""#Source3 cleaning and handling"""

df3_final = df3.assign(
    norm_name=df3['Name'].apply(normalize_name),
    norm_phone=df3['Phone Number'].apply(normalize_phone),
    norm_city=df3['City'].apply(normalize_city),
    norm_verified=df3['Verified'].apply(normalize_verified)
)[[
    'norm_name', 'norm_phone', 'norm_city','norm_verified','Projects Completed'
]]

df3_final.to_csv('df3_final.csv', index=False)